export const CHANGE_PAGENUMBER = "CHANGE_PAGENUMBER";
export const CLEAR_USERS_API_RESPONSE = "CLEAR_USERS_API_RESPONSE";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const ACTIVE_INACTIVE_USER_REQUEST = "ACTIVE_INACTIVE_USER_REQUEST";
export const ACTIVE_INACTIVE_USER_SUCCESS = "ACTIVE_INACTIVE_USER_SUCCESS";
export const ACTIVE_INACTIVE_USER_FAILURE = "ACTIVE_INACTIVE_USER_FAILURE";
export const CLEAR_ACTIVE_INACTIVE_USER_RESPONSE = "CLEAR_ACTIVE_INACTIVE_USER_RESPONSE";

