export const GET_GROUP_TYPES_FAILURE = "GET_GROUP_TYPES_FAILURE";
export const GET_GROUP_TYPES_REQUEST = "GET_GROUP_TYPES_REQUEST";
export const GET_GROUP_TYPES_SUCCESS = "GET_GROUP_TYPES_SUCCESS";
export const CLEAR_GROUP_TYPES_RESPONSE = "CLEAR_GROUP_TYPES_RESPONSE";
export const CHANGE_GROUP_FORM = "CHANGE_GROUP_FORM";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const CLEAR_USERS_RESPONSE = "CLEAR_USERS_RESPONSE";
export const CHANGE_GROUP_SETTING_VALIDATION = "CHANGE_GROUP_SETTING_VALIDATION";
export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";
export const CLEAR_CREATE_GROUP_RESPONSE = "CLEAR_CREATE_GROUP_RESPONSE";

export const DISCOVER_GROUPS_REQUEST = "DISCOVER_GROUPS_REQUEST";
export const DISCOVER_GROUPS_SUCCESS = "DISCOVER_GROUPS_SUCCESS";
export const DISCOVER_GROUPS_FAILURE = "DISCOVER_GROUPS_FAILURE";

export const MY_GROUPS_REQUEST = "MY_GROUPS_REQUEST";
export const MY_GROUPS_SUCCESS = "MY_GROUPS_SUCCESS";
export const MY_GROUPS_FAILURE = "MY_GROUPS_FAILURE";

export const CLEAR_GET_MY_GROUPS_RESPONSE = "CLEAR_GET_MY_GROUPS_RESPONSE";
export const CLEAR_GET_DISCOVER_GROUPS_RESPONSE = "CLEAR_GET_DISCOVER_GROUPS_RESPONSE";

export const DISCOVER_GROUP_DETAILS_REQUEST = "DISCOVER_GROUP_DETAILS_REQUEST";
export const DISCOVER_GROUP_DETAILS_SUCCESS = "DISCOVER_GROUP_DETAILS_SUCCESS";
export const DISCOVER_GROUP_DETAILS_FAILURE = "DISCOVER_GROUP_DETAILS_FAILURE";

export const CLEAR_DISCOVER_GROUP_DETAILS_RESPONSE = "CLEAR_DISCOVER_GROUP_DETAILS_RESPONSE";

export const GET_MY_GROUP_DETAILS_REQUEST = "GET_MY_GROUP_DETAILS_REQUEST";
export const GET_MY_GROUP_DETAILS_SUCCESS = "GET_MY_GROUP_DETAILS_SUCCESS";
export const GET_MY_GROUP_DETAILS_FAILURE = "GET_MY_GROUP_DETAILS_FAILURE";

export const CLEAR_GET_MY_GROUP_DETAILS_RESPONSE = "CLEAR_GET_MY_GROUP_DETAILS_RESPONSE";

export const GET_GROUP_TYPE_GROUPS_REQUEST = "GET_GROUP_TYPE_GROUPS_REQUEST";
export const GET_GROUP_TYPE_GROUPS_SUCCESS = "GET_GROUP_TYPE_GROUPS_SUCCESS";
export const GET_GROUP_TYPE_GROUPS_FAILURE = "GET_GROUP_TYPE_GROUPS_FAILURE";

export const CLEAR_GET_GROUP_TYPE_GROUPS_RESPONSE = "CLEAR_GET_GROUP_TYPE_GROUPS_RESPONSE";

export const CHANGE_IS_DISCOVER_STATUS = "CHANGE_IS_DISCOVER_STATUS";


export const GET_GROUP_SETTINGS_REQUEST = "GET_GROUP_SETTINGS_REQUEST";
export const GET_GROUP_SETTINGS_SUCCESS = "GET_GROUP_SETTINGS_SUCCESS";
export const GET_GROUP_SETTINGS_FAILURE = "GET_GROUP_SETTINGS_FAILURE";

export const CLEAR_USERS_AND_TYPES_STATUS = "CLEAR_USERS_AND_TYPES_STATUS";

export const CLEAR_GET_GROUP_SETTINGS_STATUS = "CLEAR_GET_GROUP_SETTINGS_STATUS";

export const DELETE_MY_GROUP_REQUEST = "DELETE_MY_GROUP_REQUEST";
export const DELETE_MY_GROUP_SUCCESS = "DELETE_MY_GROUP_SUCCESS";
export const DELETE_MY_GROUP_FAILURE = "DELETE_MY_GROUP_FAILURE";

export const LEAVE_MY_GROUP_REQUEST = "LEAVE_MY_GROUP_REQUEST";
export const LEAVE_MY_GROUP_SUCCESS = "LEAVE_MY_GROUP_SUCCESS";
export const LEAVE_MY_GROUP_FAILURE = "LEAVE_MY_GROUP_FAILURE";

export const CLEAR_DELETE_MY_GROUP_STATUS = "CLEAR_DELETE_MY_GROUP_STATUS";
export const CLEAR_LEAVE_MY_GROUP_STATUS = "CLEAR_LEAVE_MY_GROUP_STATUS";

export const REQUEST_JOIN_GROUP_REQUEST = "REQUEST_JOIN_GROUP_REQUEST";
export const REQUEST_JOIN_GROUP_SUCCESS = "REQUEST_JOIN_GROUP_SUCCESS";
export const REQUEST_JOIN_GROUP_FAILURE = "REQUEST_JOIN_GROUP_FAILURE";

export const CLEAR_REQUEST_JOIN_GROUP_STATUS = "CLEAR_REQUEST_JOIN_GROUP_STATUS";

export const ACCEPT_REJECT_GROUP_REQUEST = "ACCEPT_REJECT_GROUP_REQUEST";
export const ACCEPT_REJECT_GROUP_SUCCESS = "ACCEPT_REJECT_GROUP_SUCCESS";
export const ACCEPT_REJECT_GROUP_FAILURE = "ACCEPT_REJECT_GROUP_FAILURE";

export const CHANGE_CREATE_CHANNEL_FORM = "CHANGE_CREATE_CHANNEL_FORM";
export const CLEAR_CREATE_CHANNEL_RESPONSE = "CLEAR_CREATE_CHANNEL_RESPONSE";

export const CREATE_CHANNEL_REQUEST = "CREATE_CHANNEL_REQUEST";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAILURE = "CREATE_CHANNEL_FAILURE";

export const ACCEPT_DECLINE_GROUP_REQUEST = "ACCEPT_DECLINE_GROUP_REQUEST";
export const ACCEPT_DECLINE_GROUP_SUCCESS = "ACCEPT_DECLINE_GROUP_SUCCESS";
export const ACCEPT_DECLINE_GROUP_FAILURE = "ACCEPT_DECLINE_GROUP_FAILURE";

export const CLEAR_ACCEPT_DECLINE_GROUP_STATUS = "CLEAR_ACCEPT_DECLINE_GROUP_STATUS";

export const CHANGE_SOCKET_CONFIG = "CHANGE_SOCKET_CONFIG";

export const CLEAR_GET_MY_GROUP_DETAILS_STATUS_RESPONSE = "CLEAR_GET_MY_GROUP_DETAILS_STATUS_RESPONSE";

export const SEND_NO_CHANNEL_AND_MEMBERS_ERROR = "SEND_NO_CHANNEL_AND_MEMBERS_ERROR";

export const CHANGE_CHAT_MESSAGE = "CHANGE_CHAT_MESSAGE";

export const STOP_CHAT_CONNECTION = "STOP_CHAT_CONNECTION";

export const INVITE_USER_FAILURE = "INVITE_USER_FAILURE";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_REQUEST = "INVITE_USER_REQUEST";
export const CLEAR_INVITE_USER_RESPONSE = "CLEAR_INVITE_USER_RESPONSE";
export const CHANGE_INVITE_USER_FORM = "CHANGE_INVITE_USER_FORM";

export const CHANGE_MY_GROUPS_PAGE = "CHANGE_MY_GROUPS_PAGE";

export const TARGET_MY_GROUPS_PAGE = "TARGET_MY_GROUPS_PAGE";
